### ISSUE TITLE
CDPのトランザクションが通らなかった場合でも成功メッセージが出る

### ISSUE THREAD

**Issue by Senna46** [lcnem/botany#145]
CDPのトランザクションが通らなくても存在しないTx Hashが発行され、リダイレクトされる。

0ubtc担保、0jpyx発行のような極端な場合でも成功メッセージが表示される。

担保が少ない場合や2つ目のCDPを作成しようとしたときなどに発生。発生条件やエラーコードについては要検証。

**Comment by YasunoriMATSUOKA** [comment]
トランザクションの成功・失敗判定のロジックがそもそも実装されていないことに原因があるかもしれません。そのあたりに着目して修正する必要がありそうです。(codeを見て成功・失敗判定する必要があるが未実装である等)

**Comment by YasunoriMATSUOKA** [comment]
code === 0ではない場合と、txHash === undefined等の場合に、失敗判定できるよう実装を追加してみてください。

**Comment by YasunoriMATSUOKA** [comment]
別件の稼働とのバランス的に、もし松岡にて引き取って修正したほうが良い場合は、その旨、連絡ください。

**Comment by Senna46** [comment]
Auction同様の実装でエラーは拾って挙げられそうです。
code!==0での失敗判定で修正しておきます。失敗でもtxhashは一応発行されるのでこれを判定に使うのはよくなさそうです。

![cdp](https://user-images.githubusercontent.com/29295263/141943673-35334b27-d54b-4e23-ad1c-5494a4fe1fb8.PNG)

**Comment by YasunoriMATSUOKA** [comment]
念には念をいれてtxHash === undefinedだったらNGと判断してroutingしないとかの実装はあってもよいと思いましたが、なくてもよいと思ったので、その路線で問題ありません。

**Comment by Senna46** [comment]
code!==0の場合、リダイレクトまで走らないので現状の認識だと大丈夫だと思っています。
もし、code=0でtxHashなしということがあれば追加で実装する必要ありそうですが

**Comment by YasunoriMATSUOKA** [comment]
はい、その通りだと思うので、なくてもよいです。

**Comment by YasunoriMATSUOKA** [comment]
@Senna46 cc: @KimuraYu45z 
telescopeレポジトリのbank sendも本Issueと同じ問題を抱えていると思うので、同様に修正をお願いします。
