### ISSUE TITLE
JPYX用の設定を含むcosmoscanのデバッグ方法を検討する

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/botany#21]
cosmoscanをノードが動作していない端末上でもデバッグ可能にすべきか否か？

1. cosmoscanをノードが動作していない端末上でもデバッグできるようにする(変更必要)
2. ノードが動作している端末上でcosmoscanを動作させてデバッグする(現状維持)

cosmoscanをノードが動作していない端末上でもデバッグできるようにする場合

1. 方法は現時点ではイメージできていない

ノードが動作している端末上でcosmoscanを動作させてデバッグする場合

1. ローカルでテストネットのノード、cosmoscan等一式を動作させてデバッグする ... cosmoscanの一部のファイルを誤ってJPYX用の設定を含めてコミットしてしまうミスが起こりやすい？
2. 既にテストネットのノードが動作しているVPS上へcosmoscan, botany等のビルドが必要なリソースを展開し、VPS上でビルドしてデバッグする ... VPS上に繊細な情報が展開されることになり、セキュリティリスクが高い？

**Comment by KimuraYu45z** [comment]
ノードを動かしていない端末でもデバッグは可能です(cosmos-sdk.serviceにてエンドポイントをリテラル書き換えれば良い)が、もっと難しい問題は

「config-jpyxをコピーして適用させる」みたいなのを毎回できるかどうかだと思います。

**Comment by KimuraYu45z** [comment]
今調べたんですが、これが使えるかもしれません！
https://qiita.com/asa-taka/items/0629575a670b27726f4a

**Comment by KimuraYu45z** [comment]
To Do：

- https://github.com/lcnem/cosmoscan/pull/29 をこっちのリポジトリでもパクる
- editionsフォルダの中の`jpyx/config-jpyx.json`と`eurx/config-eurx.json`を消し、`jpyx/config.js`と`eurx/config.js`を内容埋めて作成
- docker-compose.ymlにて、`assets/config.js`をvolumeできるようにしておく
  - `editions/jpyx/config.js`はビルド前にコピーするのではなくvolumeでやればよさそう

**Comment by KimuraYu45z** [comment]
あとはconfigいじってノードのrestエンドポイント指定してデバッグする感じで！
