### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by KimuraYu45z** [lcnem/botany#25]
`projects/cosmoscan-extension`フォルダ内に`.gitignore`を作って、

`src/assets/config.js`を書く

**Comment by KimuraYu45z** [comment]
@Senna46 こっちもたのみます

**Comment by Senna46** [comment]
変更後、`gitignore`ブレンチ作成。
`sign`にマージされたのでcloseします。

**Comment by KimuraYu45z** [comment]
いや、それはcosmoscanリポジトリの話だったかと
こっちのリポジトリではまだやってないはずです。

**Comment by Senna46** [comment]
勘違いでした。やっておきます。

**Comment by KimuraYu45z** [comment]
@Senna46 issueもクローズ頼むわー
