### ISSUE TITLE
cosmoscan-eurxのDockerイメージビルドエラー

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/botany#31]
https://github.com/lcnem/botany/actions/runs/1003393186

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z @Senna46 
websiteのCD対応時にpackage-lock.jsonが大幅に変更された結果、失敗していた npm ci が成功するようになり、イメージのビルド、Docker Hubへのプッシュが成功するようになったようです。クローズしておきます。

**Comment by KimuraYu45z** [comment]
おおw
