### ISSUE TITLE
[優先度中]ブランチプロテクションルールの設定

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/botany#43]
@KimuraYu45z 
入れたほうが良いと思っていますが、もし何か特別な事情があれば相談させてください。

**Comment by KimuraYu45z** [comment]
いまのgithubのプランだと、パブリックリポジトリにのみブランチプロテクションが使える、ということだけ注意点かと思います。
jpyx関係はすべてパブリックリポジトリなので問題ないですが、受託や自社サービスリポジトリにも統一できるルールでは現状ない（コストとメリット天秤にかけて、プライベートリポジトリでもプロテクションできるようアップグレードする可能性は当然開かれている）、な感じです！

**Comment by YasunoriMATSUOKA** [comment]
main, developブランチに対して以下を設定しました。

- Require pull request reviews before merging
- Require status checks to pass before merging
