### ISSUE TITLE
CD firebase hosting error

### ISSUE THREAD

**Issue by Senna46** [lcnem/botany#53]
リリース時、CD firebase hostingが失敗する。
`.github/workflows/deploy-prod.yml`

https://github.com/lcnem/botany/actions/runs/1010770591

**Comment by KimuraYu45z** [comment]
@Senna46 issue作成時に、エラー内容のうち核心の部分をコピペする癖付けると良いと思います。

```
Warning: /home/runner/work/botany/botany/projects/website/src/view/home/home.component.css exceeded maximum budget. Budget 6.00 kB was not met by 5.82 kB with a total of 11.82 kB.



Error: /home/runner/work/botany/botany/projects/website/src/view/home/home.component.css exceeded maximum budget. Budget 10.00 kB was not met by 1.82 kB with a total of 11.82 kB.
```

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z 
firebaseのCDのエラーの件、functionsのnpm ciで発生する以下エラーですが、npm ciよりも先にnpm i -g firebase-tools等を実行する修正を加えたものの、解決できませんでした。

```
Run npm ci

> protobufjs@6.10.1 postinstall /home/runner/work/botany/botany/functions/node_modules/protobufjs
> node scripts/postinstall


> functions@undefined prepare /home/runner/work/botany/botany/functions
> firebase functions:config:get > .runtimeconfig.json

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@undefined prepare: `firebase functions:config:get > .runtimeconfig.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the functions@undefined prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-08T08_27_46_843Z-debug.log
Error: Process completed with exit code 1.
```

改めてエラーメッセージを詳細に確認したのですが、functionsのnpm scriptsのprepareに設定されている、`firebase functions:config:get > .runtimeconfig.json`が、npm の installの後に走ることになると思うのですが、このコマンドはfirebase login等でfirebaseの認証が完了している状態でないとエラーになると思うのですが認識あっているでしょうか？

その場合、CI環境でどのようにすればよいか、よい方法を考えられず、どうすればよいか迷っています。これ自体は、ローカルでエミュレーターでデバッグする際に必要という認識なのですが、CI環境では実行不要(というか認証通っていない状況でこれをエラーなく実行することは不可能なので、実行してはいけない)と思っているのですが、どうするのが適切でしょうか？

お手数ですが、ヘルプ頂けると助かります。よろしくお願いします。

**Comment by YasunoriMATSUOKA** [comment]
ようやく、Firebase の CDがFunctions含めて動作できるところまでたどり着きました。
ご協力ありがとうございましたm(__)m
https://github.com/lcnem/botany/runs/3018227732?check_suite_focus=true
