### ISSUE TITLE
[優先度高]botanyのcosmoscan-extensionでもcosmoscanと同様にcosmos-client-tsのバージョンアップに伴う修正を行う必要がある

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/botany#66]
@KimuraYu45z 
botanyのcosmoscan-jpyx, cosmoscan-eurxのビルドが失敗しました。
以下リンクのcosmoscan同様の修正を行う必要があるという理解であっているでしょうか？

Issue
https://github.com/lcnem/cosmoscan/issues/60

PR
https://github.com/lcnem/cosmoscan/pull/63

お手数ですが、念のため確認させてください。

**Comment by KimuraYu45z** [comment]
そうです。
