### ISSUE TITLE
LPのFirebase HostingのCDが正常に動作していない

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/botany#92]
websiteの修正内容を参考に修正する？

**Comment by KimuraYu45z** [comment]
ゲーッこっちもですか、、、なぜだ、、、

**Comment by KimuraYu45z** [comment]
あーいやこれは今日 @Senna46 がprettier設定変えたときに消したファイルが依存先になってて壊れたんですね。

これに関しては

https://github.com/lcnem/botany/issues/89

やれば治ると思います。
