### ISSUE TITLE
FaucetのAPIリクエストがCORSで失敗する

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/botany#93]
ノード上にデプロイしてみたのですが、CORSエラーは変わらずという状況でした。(改めて冷静に考えたらドメインはそろっても、ポート番号が違うのでCORS扱いになってしまう？)
FaucetのCLIのオプション等でCORS許可するドメインやポート指定できないか？あるいはAngularの実装を何か間違えていないか等、確認してみます。

![image](https://user-images.githubusercontent.com/55148923/134320954-7f3711d1-eeb4-41e0-9db5-696cd2393f96.png)

**Comment by KimuraYu45z** [comment]
> FaucetのCLIのオプション等でCORS許可する

↑理想形ですね。これができない場合nginxでCORS許可したリバースプロキシをdocker composeの中に同梱することになるかと思います。

**Comment by YasunoriMATSUOKA** [comment]
CLIの設定可能なパラメーターをざっと見たところ、CORSの設定はできなさそうでした
https://github.com/tendermint/faucet#configuration

nginx.confを書いて、docker-composeで同梱して、nginxでリバースプロキシ動かす作戦を試してみようと思います。
